"""The parser, one case per shape of input a real log actually contains."""
from radiorumble import adif

PLAIN = (
    "<call:6>KB0KRU <gridsquare:4>EN12 <mode:3>FT8 <rst_sent:3>+18 "
    "<rst_rcvd:3>-12 <qso_date:8>20251010 <time_on:6>015900 <band:3>40m "
    "<freq:8>7.074612 <station_callsign:6>KE0VUM <my_gridsquare:6>EM19RF <eor>"
)


def test_a_plain_adif_record_parses():
    (qso,) = adif.parse(PLAIN)
    assert qso.call == "KB0KRU"
    assert qso.station == "KE0VUM"
    assert qso.band == "40m"
    assert qso.mode == "FT8"
    assert qso.when.isoformat() == "2025-10-10T01:59:00+00:00"


def test_the_hex_dump_around_a_record_is_ignored():
    """rec.py wraps each QSO in timestamps and a hex dump of the UDP packet."""
    noisy = (
        "-" * 80 + "\n"
        "[2025-10-10 02:00:12.290] From ('192.168.1.84', 55240) (246 bytes)\n"
        "3c63616c6c3a363e4b42304b52550a\n" + PLAIN + "\n"
    )
    (qso,) = adif.parse(noisy)
    assert qso.call == "KB0KRU"


def test_a_six_character_grid_counts_as_its_four_character_square():
    """EM19 and EM19RF are the same multiplier; counting both inflates a score."""
    six = PLAIN.replace("<gridsquare:4>EN12", "<gridsquare:6>EN12ab")
    (qso,) = adif.parse(six)
    assert qso.square == "EN12"


def test_a_value_containing_spaces_is_read_by_its_declared_length():
    """The length prefix is authoritative — splitting on whitespace loses this."""
    record = "<call:6>KB0KRU <comment:9>hi  there <station_callsign:6>KE0VUM <eor>"
    (qso,) = adif.parse(record)
    assert qso.raw["comment"] == "hi  there"


def test_a_record_without_eor_is_not_returned():
    """A half-written record must wait, not be scored with missing fields."""
    assert adif.parse(PLAIN.replace("<eor>", "")) == []


def test_a_record_missing_the_station_callsign_is_dropped():
    """Nothing can attribute it to a team, so it cannot be scored."""
    assert adif.parse(PLAIN.replace("<station_callsign:6>KE0VUM ", "")) == []


def test_split_complete_holds_back_a_partial_record():
    text = PLAIN + " <call:6>KB0KR"
    complete, remainder = adif.split_complete(text)
    assert complete.endswith("<eor>")
    assert remainder.strip() == "<call:6>KB0KR"


def test_split_complete_with_no_record_keeps_everything():
    complete, remainder = adif.split_complete("<call:6>KB0KR")
    assert complete == ""
    assert remainder == "<call:6>KB0KR"


def test_a_header_before_the_first_record_is_skipped():
    """WSJT-X writes an ADIF header terminated by <eoh>."""
    text = "Generated by WSJT-X\n<adif_ver:5>3.1.0 <eoh>\n" + PLAIN
    (qso,) = adif.parse(text)
    assert qso.call == "KB0KRU"
