#!/usr/bin/env python3
"""Regenerate grid.txt from the state boundaries in static/us-states.json.

    python tools/build_grid.py

A 4-character grid square is 2 degrees of longitude by 1 of latitude — about
100 by 70 miles — so it routinely straddles a state line. This samples a
lattice of points inside each square and records every state any of them lands
in, which is the honest answer: a contact into EM19 could be in Kansas or
Nebraska and the exchange does not say which.

Hand-maintaining that mapping does not work. The list this replaces was
missing EM19 entirely — the square containing Manhattan, Kansas — while
crediting Kansas with squares that are in Colorado and Oklahoma.
"""
from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
STATES = BASE / "static" / "us-states.json"
OUTPUT = BASE / "grid.txt"

# Sample points per square, per axis. 5x5 catches a state that clips a corner
# without making the run take minutes.
SAMPLES = 5


def rings(geometry):
    """Every outer ring in a Polygon or MultiPolygon."""
    if geometry["type"] == "Polygon":
        return [geometry["coordinates"][0]]
    if geometry["type"] == "MultiPolygon":
        return [poly[0] for poly in geometry["coordinates"]]
    return []


def bbox(ring):
    xs = [p[0] for p in ring]
    ys = [p[1] for p in ring]
    return min(xs), min(ys), max(xs), max(ys)


def contains(ring, x, y) -> bool:
    """Ray casting. Good enough: we only need to know which state a point is in."""
    inside = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i]
        xj, yj = ring[j]
        if (yi > y) != (yj > y):
            if x < (xj - xi) * (y - yi) / (yj - yi + 1e-15) + xi:
                inside = not inside
        j = i
    return inside


def square_name(lon: float, lat: float) -> str:
    """South-west corner of a square to its 4-character locator."""
    lon += 180.0
    lat += 90.0
    return (
        chr(int(lon // 20) + ord("A"))
        + chr(int(lat // 10) + ord("A"))
        + str(int((lon % 20) // 2))
        + str(int(lat % 10))
    )


def main() -> None:
    data = json.loads(STATES.read_text())

    # Flatten to (state, ring, bbox) so the inner loop can skip fast.
    shapes = []
    for feature in data["features"]:
        name = feature["properties"]["name"]
        for ring in rings(feature["geometry"]):
            shapes.append((name, ring, bbox(ring)))
    print(f"{len(data['features'])} states, {len(shapes)} rings")

    # One pass over every square that could touch the country, including the
    # Aleutians west of the dateline.
    ranges = [(-180, -64), (172, 180)]
    found: dict[str, set[str]] = {}

    for lon_start, lon_end in ranges:
        lon = lon_start
        while lon < lon_end:
            lat = 18
            while lat < 72:
                name = square_name(lon, lat)
                for i in range(SAMPLES):
                    px = lon + 2.0 * (i + 0.5) / SAMPLES
                    for j in range(SAMPLES):
                        py = lat + 1.0 * (j + 0.5) / SAMPLES
                        for state, ring, (x0, y0, x1, y1) in shapes:
                            if x0 <= px <= x1 and y0 <= py <= y1 and contains(ring, px, py):
                                found.setdefault(name, set()).add(state)
                lat += 1
            lon += 2

    # Invert to state -> squares, which is the shape grid.txt stores.
    by_state: dict[str, set[str]] = {}
    for square, states in found.items():
        for state in states:
            by_state.setdefault(state, set()).add(square)

    lines = [
        "# Generated by tools/build_grid.py from static/us-states.json.",
        "# One state per line: name, then every grid square it touches.",
        "# Squares repeat across lines because a square is bigger than a border.",
    ]
    for state in sorted(by_state):
        lines.append(state + "," + ",".join(sorted(by_state[state])))
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    spans = sum(1 for s in found.values() if len(s) > 1)
    print(f"{len(found)} squares touch the US; {spans} span more than one state")
    print(f"{len(by_state)} states written to {OUTPUT.relative_to(BASE)}")


if __name__ == "__main__":
    main()
